### ISSUE TITLE
Feature request: CLI

### ISSUE THREAD

**Issue by kad** [mhausenblas/reshifter#1]
Right now reshifter works as service, which means it relies on existing infra to run that container and connectivity within that cluster.
It would be good if library behind reshifer can be utilised in the form of CLI utility which will be easy to just put on master server and perform basic one-shot ops like backup/restore, for scenarios where rest of cluster not working properly.

**Comment by mhausenblas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a CLI](https://trello.com/c/ClXrPR0v/11-create-a-cli)

**Comment by mhausenblas** [comment]
@kad here's a first, simple implementation of the CLI. Wanna try it out?
