### ISSUE TITLE
Unable to connect to etcd

### ISSUE THREAD

**Issue by ivelichkovich** [mhausenblas/reshifter#10]
### What version of Kubernetes (`kubectl  version`) are you using?
1.6.2

### What version of etcd (`etcdctl --version`) are you using?
"etcdserver":"2.2.1"
"etcdcluster":"2.2.0"

### What version of ReShifter are you using (for rcli: `rcli version` otherwise at the bottom of the app)?
Ran from yaml to deploy on cluster, image: quay.io/mhausenblas/reshifter:0.3.19

I deployed and exposed the web app of reshifter on my cluster. When I try to configure the app it doesn't work when I click explore etcd. I always get "There was a problem collecting endpoint stats: undefined". However, I can curl the same url from a pod on cluster that reshifter is unable to connect to to get the version i.e. http://{ENDPOINT}:2380/version.

**Comment by mhausenblas** [comment]
Thanks a lot for creating this issue @ivelichkovich, much easier here than via mail ;)

Now, one thing that immediately stands out it that you're using port `2380`. Did you try port `2379` as well in ReShifter and does it yield the same result?

**Comment by ivelichkovich** [comment]
I just tried 2379 and it did not work. It looks like the webapp is sending a request to localhost:8080 however.

**Comment by mhausenblas** [comment]
@ivelichkovich can it be that this is related to #7?

**Comment by mhausenblas** [comment]
Hey @ivelichkovich I'm still trying to reproduce your issue but with little success. Happy to jump on a call next week to have a look at your setup, maybe that reveals more?
