### ISSUE TITLE
can not backup resources under a project or namespace on openshift origin

### ISSUE THREAD

**Issue by vanloswang** [mhausenblas/reshifter#14]
### What version of Kubernetes (`kubectl  version`) are you using?
```bash
# kubectl  version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-25T09:55:20Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-25T09:55:20Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

### What version of etcd (`etcdctl --version`) are you using?
```bash
# etcdctl --version
etcdctl version: 3.1.9
API version: 2
```

### What version of ReShifter are you using (for rcli: `rcli version` otherwise at the bottom of the app)?
```bash
# rcli version  
0.3.21
```
Deploy reshifter app under project reshifter on openshift origin 3.6, and use following commad to backup all resources under namespace. some other configurations is backup. 
```bash
RS_ETCD_CA_CERT=/etc/origin/master/master.etcd-ca.crt RS_ETCD_CLIENT_CERT=/etc/origin/master/master.etcd-client.crt RS_ETCD_CLIENT_KEY=/etc/origin/master/master.etcd-client.key RS_BACKUP_STRATEGY=filter:/namespaces/reshifter,deploymentconfig,service,rolebindings,serviceaccount,secret,pvc rcli backup create -e https://192.168.1.5:2379
```
No such function or label seletor suppport yet? So how to backup resources under a project ? Could anyone give me some help. Thanks.

As following doc at https://docs.openshift.org/latest/admin_guide/backup_restore.html. It will backup ok.

**Comment by mhausenblas** [comment]
@vanloswang thanks for using ReShifter and for reporting this issue!

Now, how `RS_BACKUP_STRATEGY=filter:` [works](https://github.com/mhausenblas/reshifter/blob/master/docs/strategies.md) is simply that it applies whatever you have in there to the etcd path and it passes if it's in your filter. Does this make sense?

Maybe a better name would be `pass:` rather than `filter:`? Dunno.
