### ISSUE TITLE
Problems backing up OpenShift 3.6

### ISSUE THREAD

**Issue by jthiatt** [mhausenblas/reshifter#19]
### What version of Kubernetes (`kubectl  version`) are you using?
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-10-11T22:44:25Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+5115d708d7", GitCommit:"fff65cf", GitTreeState:"clean", BuildDate:"2017-08-28T09:00:00Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

### What version of etcd (`etcdctl --version`) are you using?
etcdctl version: 3.2.9
API version: 2

### What version of ReShifter are you using (for rcli: `rcli version` otherwise at the bottom of the app)?
0.3.21

### Development only: what version of Go (`go version`) and `dep` (`git describe --tags`) are you using?
N/A

When I try to backup OpenShift 3.6 I get the following error
ERRO[0000] rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4474151 vs. 4194304)

My script

`export RS_ETCD_API_VERSION="v2"`
`export RS_ETCD_CLIENT_CERT="/etc/origin/master/master.etcd-client.crt"`
`export RS_ETCD_CLIENT_KEY="/etc/origin/master/master.etcd-client.key"`
`export RS_ETCD_CA_CERT="/etc/origin/master/master.etcd-ca.crt"`
`export RS_BACKUP_STRATEGY="filter:service"`

`./rcli-linux backup create --endpoint https://sever:2379`
`./rcli-linux backup stats --endpoint https://sever:2379`

Output
**ERRO[0000] Can't find well-known v2 keyspaces**
**Collecting stats from etcd endpoint https://server:2379**
**INFO[0000] Didn't find legacy keys, trying modern keys now …**
**ERRO[0000] Having problems calculating stats: 100: Key not found (/kubernetes.io) [506246]**

What am I missing?

**Comment by mhausenblas** [comment]
Thanks for raising this issue @jthiatt, will have a look into it ASAP! Just quickly checking, what does `curl http:/server:2379/v2/keys/kubernetes.io/` give you?

**Comment by jthiatt** [comment]
Thanks for the quick response!  Output below.

curl -vv   http://server:2379/v2/keys/kubernetes.io/
* About to connect(X.X.X.X) to server port 2379 (#0)
*   Trying IP...
* Connected to server (X.X.X.X) port 2379 (#0)
> GET /v2/keys/kubernetes.io/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: server:2379
> Accept: */*
>

* Connection #0 to host server left intact

**Comment by mhausenblas** [comment]
So this suggests that you can't even get to etcd with `curl`, right?

**Comment by jthiatt** [comment]
Yeah, after looking around my etcd cluster I think I have a bigger problem.  It seems to be in an unhealthy state post-upgrade.  Thanks for pointing me in the right direction.

**Comment by mhausenblas** [comment]
Got it, thanks for investigating @jthiatt. Let me know how it goes …
