### ISSUE TITLE
Question on S3 Storage

### ISSUE THREAD

**Issue by sreekanth-ragi** [mhausenblas/reshifter#20]
### What version of Kubernetes (`kubectl  version`) are you using?
1.4.0+776c994

### What version of etcd (`etcdctl --version`) are you using?
3.2.9

### What version of ReShifter are you using (for rcli: `rcli version` otherwise at the bottom of the app)?
0.3.21

### Development only: what version of Go (`go version`) and `dep` (`git describe --tags`) are you using?

I think this should be fairly simple and quick question to answer. 
Do we support writing different etcd backup's into one S3 bucket using folder names as differentiator. Something like I have env1,env2 and in S3 I create a bucket by the name reshifter-backup and then for each of the environments I create a seperate folder, so environment 1 backup goes to env1 folder and so on.

Thanks for your time and efforts, Really appreciate it.

Sreekanth

**Comment by mhausenblas** [comment]
Thanks for raising this issue @sreekanth-ragi and the answer is yes. Since each backup is a timestamped ZIP file, this is trivially supported. See also the [CLI walkthrough](https://github.com/mhausenblas/reshifter/blob/master/docs/walkthroughs.md#cli) for more details.

**Comment by sreekanth-ragi** [comment]
Hi Michael,

Thanks for the quick turnaround, I just tried using the following command and it did not work

rcli backup create <etcd:port> --bucket  bktname/foldername --remote s3.amazonaws.com

It returned with the error.
ERRO[0081] Bucket name contains invalid characters

What am I doing wrong?
