### ISSUE TITLE
Writing back-up to folder in S3 bucket.

### ISSUE THREAD

**Issue by sreekanth-ragi** [mhausenblas/reshifter#21]
Hi Michael,

Following up on my question earlier in the day, I tried writing the backup to a folder name and following is the result.

rcli backup create etcd:port --bucket bktname/foldername --remote s3.amazonaws.com

It returned with the error.
ERRO[0081] Bucket name contains invalid characters

What am I doing wrong?

Thanks,
Sreekanth

**Comment by mhausenblas** [comment]
Drop the foldername, only `--bucket bktname`

**Comment by sreekanth-ragi** [comment]
In which it is writing directly under the bucket, does not go into the folder present inside the bucket.

**Comment by mhausenblas** [comment]
Yup, that's as it should be, no folder support at present I'm afraid.

**Comment by sreekanth-ragi** [comment]
@mhausenblas : Thank you for the confirmation.
