### ISSUE TITLE
Compatibility with GKE?

### ISSUE THREAD

**Issue by paurullan** [mhausenblas/reshifter#25]
Is this tool compatible or connectable to a running GKE cluster? I have been trying and reading the documentation but without luck.

### What version of Kubernetes (`kubectl  version`) are you using?

1.9.7 GKE

Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.0", GitCommit:"1883ce4eb0e057cfc2439ebeb9822da0a9d40405", GitTreeState:"clean", BuildDate:"2018-04-19T17:08:34Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

### What version of etcd (`etcdctl --version`) are you using?

No accesible - using GKE

### What version of ReShifter are you using (for rcli: `rcli version` otherwise at the bottom of the app)?

0.3.21

**Comment by mhausenblas** [comment]
@paurullan thanks for raising this issue! No, it won't work on GKE since it directly talks with `etcd` and AFAIK the control plane is not directly accessible in GKE.
