### ISSUE TITLE
Remove usages of localhost in client code

### ISSUE THREAD

**Issue by debben** [mhausenblas/reshifter#7]
### What version of Kubernetes (`kubectl  version`) are you using?
1.6

### What version of etcd (`etcdctl --version`) are you using?
v3

### What version of ReShifter are you using (for rcli: `rcli version` otherwise at the bottom of the app)?
0.3.19

According to the documentation:

> Note: the above YAML file defines both a Deployment as well as a Service object for ReShifter. It does, however, not expose the ReShifter service to the outside world. If you want to access the app from outside the cluster, you'll have to use Ingress or adapt the YAML file yourself.

I was able to install the UI on my cluster. I could access it both using kubectl proxy as well as by adding an ingress resource. In each case though, I couldn't actually run a backup as it seems the client-side code in ui/coreui/js/app.js is explicitly set to use localhost:8080.

I was able to get around this by using [http-proxy](https://www.npmjs.com/package/http-proxy-cli). Does app.js need to have these explicit usages of localhost:8080 for the url? Could it be changed to always use the host of whatever url the page was served from as the host for subsequent requests in app.js?

**Comment by mhausenblas** [comment]
Thanks @debben for reporting this and for using ReShifter! Hmmm, does it have to be `localhost:8080`? Well the reason really was that the Web UI is packaged along with the HTTP API in the container image, so guaranteed to be accessible from `localhost`. Maybe I'm missing something and looking at #3 (which I believe is related if not the same issue) I think we should change this, yes. I'm super open to it, so let me know if you plan to send in a PR or I should take care of it, please?

**Comment by mhausenblas** [comment]
@debben can you let me know please how you want to proceed?

**Comment by debben** [comment]
Sorry for the delay. I'll submit a PR soon.

**Comment by mhausenblas** [comment]
Thank you @debben!

**Comment by kvmprashanth** [comment]
Could you please update the image file in the below link from version 3.19 to 3.21 ?
https://raw.githubusercontent.com/mhausenblas/reshifter/master/deployments/reshifter-app.yaml

**Comment by mhausenblas** [comment]
@kvmprashanth done. Thanks for spotting this!
