### ISSUE TITLE
Unable to get the pod up and runnning

### ISSUE THREAD

**Issue by sreekanth-ragi** [mhausenblas/reshifter#8]
### What version of Kubernetes (`kubectl  version`) are you using?
OpenShift Master:   v1.5.1
Kubernetes Master: v1.5.2+43a9be4 

### What version of etcd (`etcdctl --version`) are you using?
etcdctl version: 3.1.9
API version: 2

### What version of ReShifter are you using (for rcli: `rcli version` otherwise at the bottom of the app)?
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+43a9be4", GitCommit:"43a9be4", GitTreeState:"clean", BuildDate:"2017-05-24T15:22:02Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"

### Development only: what version of Go (`go version`) and `dep` (`git describe --tags`) are you using?
v0.3.14-alpha-6-g62c1c3f

Issue:
Unable to get the pod up and running.
 Error:
Getting exec error. Following are the pod logs.

panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
--

[reshifter-app-1-0z5jb.log.txt](https://github.com/mhausenblas/reshifter/files/1168936/reshifter-app-1-0z5jb.log.txt)

**Comment by Stubbornz** [comment]
Hello Michael,
I was trying to evaluate Re-Shift for an internal project but I'm getting the above error when trying to bring up the pod. Any help is highly appreciated.

Thanks,
Sreekanth

**Comment by mhausenblas** [comment]
Sreekanth, thanks for trying ReShifter! Now, I'm trying to figure what exactly you are doing so that I can help you here. So, can you please clarify: are you trying to launch the app? And if so, using what command?

**Comment by sreekanth-ragi** [comment]
Hi Michael, 
Appreciate your quick response, I cloned the repo and tried the command given for deploying it on Openshift.

make init 
make publish

After the above commands when I login to my openshift console, I can see the pod up but it is crashing frequently, with the logs showing the error that I attached as per my initial query.

Thanks,
Sreekanth

**Comment by mhausenblas** [comment]
Ah, got it, thanks @sreekanth-ragi for clarifying this. Let me try it out again (has been some time) and come back to you and share if I can replicate it or not, OK?

**Comment by sreekanth-ragi** [comment]
Sure Michael, appreciate all your help

Thanks,
Sreekanth

**Comment by mhausenblas** [comment]
Ah, I already know what it is :)

I moved the app to `app/` around 4c6356e12adae8f0344726c9d32e0005fdd99f95 but never got to update the OpenShift-related build commands, my bad :(

There should really be test cases for this!

**Comment by sreekanth-ragi** [comment]
Awesome Michael, so could I simply do a git clone now and will be good to go or you would need more time to fix it.

Thanks again for all your efforts and help

Sreekanth

**Comment by mhausenblas** [comment]
I'm testing it ATM and yes, once done you only need a `git pull` (not clone) and you should be good.

**Comment by sreekanth-ragi** [comment]
Sure Michael, will await for your test results.

**Comment by mhausenblas** [comment]
Update: still on it, seems to be a little bit more complicated bug (the other thing mentioned above was also due to be fixed but the harder one is the OCI runtime error). So, please stand by, first thing in the morning I'll look into …

**Comment by mhausenblas** [comment]
OK, figured it out thanks to the awesome @soltysh … the fix is coming very soon now @sreekanth-ragi

**Comment by mhausenblas** [comment]
@sreekanth-ragi can you do a `git pull` and then try again the `make init` please?

**Comment by sreekanth-ragi** [comment]
@mhausenblas : Build process is failing with the following error

Step 9 : RUN curl -sf -L 'https://github.com/mhausenblas/reshifter/releases/download/v'$rversion'-alpha/reshifter' -o reshifter &&     chmod +x reshifter

EnvVar Value for rversion=0.3.20
--

**Comment by sreekanth-ragi** [comment]
Looks like it is an issue with github certificates, I'm not able to open the link directly from the browser either with a security/phishing warning being thrown.

**Comment by mhausenblas** [comment]
So @sreekanth-ragi you're saying that you can't (in your browser) download from https://github.com/mhausenblas/reshifter/releases/download/v0.3.20-alpha/reshifter yes?

**Comment by mhausenblas** [comment]
Can you do me a favour @sreekanth-ragi and do a `make build` now, should resolve it …

**Comment by mhausenblas** [comment]
OK, so once you've sorted out the cert issue, can you do the `make build` then? I've [updated](https://github.com/mhausenblas/reshifter/commit/199d7e1a9088752d41b8bcd57fdfd6beb8c844df) the instructions accordingly …

**Comment by sreekanth-ragi** [comment]
@mhausenblas : Sure will let you know once I run the build

**Comment by sreekanth-ragi** [comment]
@mhausenblas: I was able to run the build successfully and can now see the pod deployed.Thank you a lot for all your efforts and support in getting this resolved.

Thanks,
Sreekanth

**Comment by mhausenblas** [comment]
Thanks for the confirmation @sreekanth-ragi and glad to see the outcome. Closing this one now.
